version: '1.0'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-data/redis-data:/data
    ports:
      - 6379:6379

  api:
    image: panf.api
    build: .
    restart: on-failure
    depends_on:
      - db
      - redis
    volumes:
      - ./:/usr/src/app
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
